name: Benchmark

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.9]
        poetry-version: [1.1.13]
        os: [ubuntu-18.04, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run image
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: ${{ matrix.poetry-version }}
      - name: Install dependecies
        run: poetry install --remove-untracked
      - name: Execute testbench
        run: poetry run tox
      - uses: actions/upload-artifact@v2
        with:
          path: doc
          name: doc-${{ matrix.os }}
      - uses: papeloto/action-zip@v1
        with:
          files: doc
          dest: doc-${{ matrix.os }}.zip
      - name: Authenticate to GCP
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCP_SECRET }}
      - name: Upload to GCP
        uses: google-github-actions/upload-cloud-storage@v0
        with:
          gzip: true
          path: doc-${{ matrix.os }}.zip
          destination: orjson-benchmark/doc-${{ matrix.os }}.zip
      
